name       : fcitx
version    : 4.2.9.7
release    : 3
source     :
    - https://github.com/fcitx/fcitx/archive/4.2.9.7.tar.gz : 92241f0138a465347ce4dbfbcea22b513749ab7709c03e8dceb33277111ca845
    - https://download.fcitx-im.org/data/en_dict-20121020.tar.gz : c44a5d7847925eea9e4d2d04748d442cd28dd9299a0b572ef7d91eac4f5a6ceb
    - https://download.fcitx-im.org/data/py_table-20121124.tar.gz : 42146ac97de6c13d55f9e99ed873915f4c66739e9c11532a34556badf9792c04
    - https://download.fcitx-im.org/data/py_stroke-20121124.tar.gz : 8eb128a9bfa43952e67cf2fcee1fd134c6f4cfd317bc2f6c38a615f5eb64e248
    - https://download.fcitx-im.org/data/pinyin.tar.gz : 583829b24a758c087c08de4a69480d0bf5946354fe77db360d6d7f467c2bd8e1
    - https://download.fcitx-im.org/data/table.tar.gz : 6196053c724125e3ae3d8bd6b2f9172d0c83b65b0d410d3cde63b7a8d6ab87b7
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.core
summary    : A Flexible Input Method Framework
description: |
    Fcitx is an input method framework with extension support. It has three built-in Input Method Engine, Pinyin, QuWei and Table-based input methods.
patterns   :
    - gtk2 : /usr/lib/gtk-2.0
    - gtk3 : /usr/lib/gtk-3.0
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - pkgconfig(lua)
    - pkgconfig(opencc)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - extra-cmake-modules
environment: |
    export LD_PRELOAD=""
setup      : |
    cp $sources/en_dict-20121020.tar.gz   $workdir/src/module/spell/dict/
    cp $sources/py_table-20121124.tar.gz  $workdir/src/module/pinyin-enhance/data/
    cp $sources/py_stroke-20121124.tar.gz $workdir/src/module/pinyin-enhance/data/
    cp $sources/pinyin.tar.gz             $workdir/src/im/pinyin/data/
    cp $sources/table.tar.gz              $workdir/src/im/table/data/
    sed -e 's|enchant/enchant.h|enchant-2/enchant.h|' \
        -e 's|PC_ENCHANT enchant|&-2|' -i cmake/FindEnchant.cmake

    %cmake_ninja \
        -DSYSCONFDIR=/usr/share \
        -DFORCE_OPENCC=ON \
        -DFORCE_PRESAGE=ON \
        -DFORCE_ENCHANT=ON \
        -DENABLE_GIR=ON \
        -DENABLE_GTK2_IM_MODULE=ON \
        -DENABLE_GTK3_IM_MODULE=ON \
        -DENABLE_LUA=ON \
        -DENABLE_QT=OFF \
        -DENABLE_TESTING=OFF \
        -DENCHANT_INCLUDE_DIR=/usr/include/enchant-2 \
        -DENCHANT_LIBRARIES=/usr/lib64/libenchant-2.so
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00755 $pkgfiles/50-fcitx.sh $installdir/usr/share/defaults/etc/profile.d/50-fcitx.sh
    rm $installdir/usr/share/applications/fcitx-configtool.desktop
